// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package pgdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createInboxEvent = `-- name: CreateInboxEvent :one
INSERT INTO inbox_events (
    id,
    topic,
    key,
    type,
    version,
    producer,
    payload,
    status,
    attempts,
    next_retry_at,
    processed_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,  $10, $11
)
ON CONFLICT (id) DO NOTHING
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
`

type CreateInboxEventParams struct {
	ID          uuid.UUID
	Topic       string
	Key         string
	Type        string
	Version     int32
	Producer    string
	Payload     json.RawMessage
	Status      InboxEventStatus
	Attempts    int32
	NextRetryAt sql.NullTime
	ProcessedAt sql.NullTime
}

func (q *Queries) CreateInboxEvent(ctx context.Context, arg CreateInboxEventParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createInboxEvent,
		arg.ID,
		arg.Topic,
		arg.Key,
		arg.Type,
		arg.Version,
		arg.Producer,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.ProcessedAt,
	)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getInboxEventByID = `-- name: GetInboxEventByID :one
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
FROM inbox_events
WHERE id = $1
`

func (q *Queries) GetInboxEventByID(ctx context.Context, id uuid.UUID) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, getInboxEventByID, id)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPendingInboxEvents = `-- name: GetPendingInboxEvents :many
WITH picked AS (
    SELECT id
    FROM inbox_events
    WHERE status = 'pending'
      AND (next_retry_at IS NULL OR next_retry_at <= now() AT TIME ZONE 'UTC')
    ORDER BY seq ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE inbox_events i
    SET status = 'processing'
    FROM picked p
    WHERE i.id = p.id
    RETURNING i.id, i.seq, i.topic, i.key, i.type, i.version, i.producer, i.payload, i.status, i.attempts, i.created_at, i.next_retry_at, i.processed_at
)
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
FROM updated
ORDER BY seq ASC
`

type GetPendingInboxEventsRow struct {
	ID          uuid.UUID
	Seq         int64
	Topic       string
	Key         string
	Type        string
	Version     int32
	Producer    string
	Payload     json.RawMessage
	Status      InboxEventStatus
	Attempts    int32
	CreatedAt   time.Time
	NextRetryAt sql.NullTime
	ProcessedAt sql.NullTime
}

func (q *Queries) GetPendingInboxEvents(ctx context.Context, limit int32) ([]GetPendingInboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingInboxEventsRow
	for rows.Next() {
		var i GetPendingInboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxEventsAsFailed = `-- name: MarkInboxEventsAsFailed :many
UPDATE inbox_events
SET
    status = 'failed',
    next_retry_at = NULL
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
`

func (q *Queries) MarkInboxEventsAsFailed(ctx context.Context, ids []uuid.UUID) ([]InboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markInboxEventsAsFailed, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxEvent
	for rows.Next() {
		var i InboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxEventsAsPending = `-- name: MarkInboxEventsAsPending :many
UPDATE inbox_events
SET
    status = 'pending',
    attempts = attempts + 1,
    next_retry_at = $1::timestamptz
WHERE id = ANY($2::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
`

type MarkInboxEventsAsPendingParams struct {
	NextRetryAt time.Time
	Ids         []uuid.UUID
}

func (q *Queries) MarkInboxEventsAsPending(ctx context.Context, arg MarkInboxEventsAsPendingParams) ([]InboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markInboxEventsAsPending, arg.NextRetryAt, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxEvent
	for rows.Next() {
		var i InboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxEventsAsProcessed = `-- name: MarkInboxEventsAsProcessed :many
UPDATE inbox_events
SET
    status = 'processed',
    processed_at = now() AT TIME ZONE 'UTC'
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
`

func (q *Queries) MarkInboxEventsAsProcessed(ctx context.Context, ids []uuid.UUID) ([]InboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markInboxEventsAsProcessed, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxEvent
	for rows.Next() {
		var i InboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInboxEventStatus = `-- name: UpdateInboxEventStatus :one
UPDATE inbox_events
SET status = $1::inbox_event_status
WHERE id = $2::uuid
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, processed_at
`

type UpdateInboxEventStatusParams struct {
	Status InboxEventStatus
	ID     uuid.UUID
}

func (q *Queries) UpdateInboxEventStatus(ctx context.Context, arg UpdateInboxEventStatusParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, updateInboxEventStatus, arg.Status, arg.ID)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.ProcessedAt,
	)
	return i, err
}
