// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type InboxEventStatus string

const (
	InboxEventStatusPending   InboxEventStatus = "pending"
	InboxEventStatusProcessed InboxEventStatus = "processed"
	InboxEventStatusFailed    InboxEventStatus = "failed"
)

func (e *InboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxEventStatus(s)
	case string:
		*e = InboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxEventStatus: %T", src)
	}
	return nil
}

type NullInboxEventStatus struct {
	InboxEventStatus InboxEventStatus
	Valid            bool // Valid is true if InboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxEventStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending OutboxEventStatus = "pending"
	OutboxEventStatusSent    OutboxEventStatus = "sent"
	OutboxEventStatusFailed  OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus
	Valid             bool // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type InboxEvent struct {
	ID             uuid.UUID
	Seq            int64
	Topic          string
	Key            string
	Type           string
	Version        int32
	Producer       string
	Payload        json.RawMessage
	Status         InboxEventStatus
	Attempts       int32
	LastAttemptAt  time.Time
	CreatedAt      time.Time
	KafkaPartition sql.NullInt32
	KafkaOffset    sql.NullInt64
	NextRetryAt    time.Time
	ProcessedAt    sql.NullTime
}

type InboxKeyLock struct {
	Key      string
	Owner    string
	LockedAt time.Time
	StaleAt  time.Time
}

type InboxKeyState struct {
	Key          string
	BlockedUntil sql.NullTime
	UpdatedAt    time.Time
}

type OutboxEvent struct {
	ID            uuid.UUID
	Seq           int64
	Topic         string
	Key           string
	Type          string
	Version       int32
	Producer      string
	Payload       json.RawMessage
	Status        OutboxEventStatus
	Attempts      int32
	LastAttemptAt sql.NullTime
	CreatedAt     time.Time
	NextRetryAt   time.Time
	SentAt        sql.NullTime
}

type OutboxKeyLock struct {
	Key      string
	Owner    string
	LockedAt time.Time
	StaleAt  time.Time
}

type OutboxKeyState struct {
	Key          string
	BlockedUntil sql.NullTime
	UpdatedAt    time.Time
}
