// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package pgdb

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id,
    topic,
    type,
    version,
    key,
    producer,
    payload,
    status,
    attempts,
    next_retry_at,
    sent_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9,  $10, $11
)
ON CONFLICT (id) DO NOTHING
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
`

type CreateOutboxEventParams struct {
	ID          uuid.UUID
	Topic       string
	Type        string
	Version     int32
	Key         string
	Producer    string
	Payload     json.RawMessage
	Status      OutboxEventStatus
	Attempts    int32
	NextRetryAt sql.NullTime
	SentAt      sql.NullTime
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.Type,
		arg.Version,
		arg.Key,
		arg.Producer,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.SentAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.SentAt,
	)
	return i, err
}

const getOutboxEventByID = `-- name: GetOutboxEventByID :one
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
FROM outbox_events
WHERE id = $1
`

func (q *Queries) GetOutboxEventByID(ctx context.Context, id uuid.UUID) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, getOutboxEventByID, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.SentAt,
	)
	return i, err
}

const getPendingOutboxEvents = `-- name: GetPendingOutboxEvents :many
WITH picked AS (
    SELECT id
    FROM outbox_events
    WHERE status = 'pending'
      AND (next_retry_at IS NULL OR next_retry_at <= now() AT TIME ZONE 'UTC')
    ORDER BY seq ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
),
updated AS (
    UPDATE outbox_events o
    SET status = 'processing'
    FROM picked p
    WHERE o.id = p.id
    RETURNING o.id, o.seq, o.topic, o.key, o.type, o.version, o.producer, o.payload, o.status, o.attempts, o.created_at, o.next_retry_at, o.sent_at
)
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
FROM updated
ORDER BY seq ASC
`

type GetPendingOutboxEventsRow struct {
	ID          uuid.UUID
	Seq         int64
	Topic       string
	Key         string
	Type        string
	Version     int32
	Producer    string
	Payload     json.RawMessage
	Status      OutboxEventStatus
	Attempts    int32
	CreatedAt   time.Time
	NextRetryAt sql.NullTime
	SentAt      sql.NullTime
}

func (q *Queries) GetPendingOutboxEvents(ctx context.Context, limit int32) ([]GetPendingOutboxEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingOutboxEventsRow
	for rows.Next() {
		var i GetPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsFailed = `-- name: MarkOutboxEventsAsFailed :many
UPDATE outbox_events
SET
    status = 'failed',
    next_retry_at = NULL
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
`

func (q *Queries) MarkOutboxEventsAsFailed(ctx context.Context, ids []uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsFailed, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsPending = `-- name: MarkOutboxEventsAsPending :many
UPDATE outbox_events
SET
    status = 'pending',
    attempts = attempts + 1,
    next_retry_at = $1::timestamptz
WHERE id = ANY($2::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
`

type MarkOutboxEventsAsPendingParams struct {
	NextRetryAt time.Time
	Ids         []uuid.UUID
}

func (q *Queries) MarkOutboxEventsAsPending(ctx context.Context, arg MarkOutboxEventsAsPendingParams) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsPending, arg.NextRetryAt, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsSent = `-- name: MarkOutboxEventsAsSent :many
UPDATE outbox_events
SET
    status = 'sent',
    sent_at = now() AT TIME ZONE 'UTC'
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, created_at, next_retry_at, sent_at
`

func (q *Queries) MarkOutboxEventsAsSent(ctx context.Context, ids []uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsSent, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
