// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_key_state.sql

package pgdb

import (
	"context"
	"time"
)

const clearInboxKeyStateBlock = `-- name: ClearInboxKeyStateBlock :exec
UPDATE inbox_key_state
SET blocked_until = NULL,
    updated_at    = (now() AT TIME ZONE 'UTC')
WHERE key = $1::text
`

func (q *Queries) ClearInboxKeyStateBlock(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, clearInboxKeyStateBlock, key)
	return err
}

const getInboxKeyState = `-- name: GetInboxKeyState :one
SELECT key, blocked_until, updated_at
FROM inbox_key_state
WHERE key = $1::text
`

func (q *Queries) GetInboxKeyState(ctx context.Context, key string) (InboxKeyState, error) {
	row := q.db.QueryRowContext(ctx, getInboxKeyState, key)
	var i InboxKeyState
	err := row.Scan(&i.Key, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const listBlockedInboxKeys = `-- name: ListBlockedInboxKeys :many
SELECT key, blocked_until, updated_at
FROM inbox_key_state
WHERE blocked_until IS NOT NULL
    AND blocked_until > (now() AT TIME ZONE 'UTC')
ORDER BY blocked_until ASC
`

func (q *Queries) ListBlockedInboxKeys(ctx context.Context) ([]InboxKeyState, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedInboxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InboxKeyState
	for rows.Next() {
		var i InboxKeyState
		if err := rows.Scan(&i.Key, &i.BlockedUntil, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInboxKeyStateBlock = `-- name: UpsertInboxKeyStateBlock :exec
INSERT INTO inbox_key_state(key, blocked_until, updated_at)
VALUES (
    $1::text,
    $2::timestamptz,
    (now() AT TIME ZONE 'UTC')
)
ON CONFLICT (key) DO UPDATE
SET blocked_until = EXCLUDED.blocked_until,
    updated_at    = (now() AT TIME ZONE 'UTC')
`

type UpsertInboxKeyStateBlockParams struct {
	Key          string
	BlockedUntil time.Time
}

func (q *Queries) UpsertInboxKeyStateBlock(ctx context.Context, arg UpsertInboxKeyStateBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertInboxKeyStateBlock, arg.Key, arg.BlockedUntil)
	return err
}
