// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox_key_locks.sql

package pgdb

import (
	"context"
	"time"
)

const deleteStaleInboxKeyLocks = `-- name: DeleteStaleInboxKeyLocks :exec
DELETE FROM inbox_key_locks
WHERE stale_at <= (now() AT TIME ZONE 'UTC')
`

func (q *Queries) DeleteStaleInboxKeyLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStaleInboxKeyLocks)
	return err
}

const getInboxKeyLock = `-- name: GetInboxKeyLock :one
SELECT key, owner, locked_at, stale_at
FROM inbox_key_locks
WHERE key = $1::text
`

func (q *Queries) GetInboxKeyLock(ctx context.Context, key string) (InboxKeyLock, error) {
	row := q.db.QueryRowContext(ctx, getInboxKeyLock, key)
	var i InboxKeyLock
	err := row.Scan(
		&i.Key,
		&i.Owner,
		&i.LockedAt,
		&i.StaleAt,
	)
	return i, err
}

const tryLockInboxKey = `-- name: TryLockInboxKey :one
INSERT INTO inbox_key_locks(key, owner, locked_at, stale_at)
SELECT
    $1::text,
    $2::text,
    (now() AT TIME ZONE 'UTC'),
    $3::timestamptz
WHERE NOT EXISTS (
    SELECT 1
    FROM inbox_key_state ks
    WHERE ks.key = $1::text
        AND ks.blocked_until IS NOT NULL
        AND ks.blocked_until > (now() AT TIME ZONE 'UTC')
)
ON CONFLICT (key) DO UPDATE
SET owner     = EXCLUDED.owner,
    locked_at = EXCLUDED.locked_at,
    stale_at  = EXCLUDED.stale_at
WHERE inbox_key_locks.stale_at <= (now() AT TIME ZONE 'UTC')
RETURNING key, owner, locked_at, stale_at
`

type TryLockInboxKeyParams struct {
	Key     string
	Owner   string
	StaleAt time.Time
}

func (q *Queries) TryLockInboxKey(ctx context.Context, arg TryLockInboxKeyParams) (InboxKeyLock, error) {
	row := q.db.QueryRowContext(ctx, tryLockInboxKey, arg.Key, arg.Owner, arg.StaleAt)
	var i InboxKeyLock
	err := row.Scan(
		&i.Key,
		&i.Owner,
		&i.LockedAt,
		&i.StaleAt,
	)
	return i, err
}

const unlockInboxKey = `-- name: UnlockInboxKey :exec
DELETE FROM inbox_key_locks
WHERE key = $1::text
  AND owner = $2::text
`

type UnlockInboxKeyParams struct {
	Key   string
	Owner string
}

func (q *Queries) UnlockInboxKey(ctx context.Context, arg UnlockInboxKeyParams) error {
	_, err := q.db.ExecContext(ctx, unlockInboxKey, arg.Key, arg.Owner)
	return err
}
