// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_key_state.sql

package pgdb

import (
	"context"
	"time"
)

const clearOutboxKeyStateBlock = `-- name: ClearOutboxKeyStateBlock :exec
UPDATE outbox_key_state
SET blocked_until = NULL,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE key = $1::text
`

func (q *Queries) ClearOutboxKeyStateBlock(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, clearOutboxKeyStateBlock, key)
	return err
}

const getOutboxKeyState = `-- name: GetOutboxKeyState :one
SELECT key, blocked_until, updated_at
FROM outbox_key_state
WHERE key = $1::text
`

func (q *Queries) GetOutboxKeyState(ctx context.Context, key string) (OutboxKeyState, error) {
	row := q.db.QueryRowContext(ctx, getOutboxKeyState, key)
	var i OutboxKeyState
	err := row.Scan(&i.Key, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const upsertOutboxKeyStateBlock = `-- name: UpsertOutboxKeyStateBlock :exec
INSERT INTO outbox_key_state(key, blocked_until, updated_at)
VALUES (
    $1::text,
    $2::timestamptz,
    (now() AT TIME ZONE 'UTC')
)
ON CONFLICT (key) DO UPDATE
    SET blocked_until = EXCLUDED.blocked_until,
    updated_at = (now() AT TIME ZONE 'UTC')
`

type UpsertOutboxKeyStateBlockParams struct {
	Key          string
	BlockedUntil time.Time
}

func (q *Queries) UpsertOutboxKeyStateBlock(ctx context.Context, arg UpsertOutboxKeyStateBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertOutboxKeyStateBlock, arg.Key, arg.BlockedUntil)
	return err
}
