// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package pgdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id, topic, key, type, version, producer, payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
`

type CreateOutboxEventParams struct {
	ID       uuid.UUID
	Topic    string
	Key      string
	Type     string
	Version  int32
	Producer string
	Payload  json.RawMessage
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createOutboxEvent,
		arg.ID,
		arg.Topic,
		arg.Key,
		arg.Type,
		arg.Version,
		arg.Producer,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.SentAt,
	)
	return i, err
}

const getOutboxEventByID = `-- name: GetOutboxEventByID :one
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
FROM outbox_events
WHERE id = $1
`

func (q *Queries) GetOutboxEventByID(ctx context.Context, id uuid.UUID) (OutboxEvent, error) {
	row := q.db.QueryRowContext(ctx, getOutboxEventByID, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.Topic,
		&i.Key,
		&i.Type,
		&i.Version,
		&i.Producer,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
		&i.NextRetryAt,
		&i.SentAt,
	)
	return i, err
}

const getPendingOutboxEventsByKey = `-- name: GetPendingOutboxEventsByKey :many
SELECT id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
FROM outbox_events
WHERE status = 'pending'
    AND key = $2::text
    AND next_retry_at <= (now() AT TIME ZONE 'UTC')
ORDER BY seq ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetPendingOutboxEventsByKeyParams struct {
	Limit int32
	Key   string
}

func (q *Queries) GetPendingOutboxEventsByKey(ctx context.Context, arg GetPendingOutboxEventsByKeyParams) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, getPendingOutboxEventsByKey, arg.Limit, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsFailed = `-- name: MarkOutboxEventsAsFailed :many
UPDATE outbox_events
SET
    status = 'failed',
    attempts = attempts + 1,
    last_attempt_at = (now() AT TIME ZONE 'UTC')
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
`

func (q *Queries) MarkOutboxEventsAsFailed(ctx context.Context, ids []uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsFailed, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsPending = `-- name: MarkOutboxEventsAsPending :many
UPDATE outbox_events
SET
    status = 'pending',
    next_retry_at = $1::timestamptz
WHERE id = ANY($2::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
`

type MarkOutboxEventsAsPendingParams struct {
	NextRetryAt time.Time
	Ids         []uuid.UUID
}

func (q *Queries) MarkOutboxEventsAsPending(ctx context.Context, arg MarkOutboxEventsAsPendingParams) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsPending, arg.NextRetryAt, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventsAsSent = `-- name: MarkOutboxEventsAsSent :many
UPDATE outbox_events
SET
    status = 'sent',
    attempts = attempts + 1,
    last_attempt_at = (now() AT TIME ZONE 'UTC'),
    sent_at = (now() AT TIME ZONE 'UTC')
WHERE id = ANY($1::uuid[])
RETURNING id, seq, topic, key, type, version, producer, payload, status, attempts, last_attempt_at, created_at, next_retry_at, sent_at
`

func (q *Queries) MarkOutboxEventsAsSent(ctx context.Context, ids []uuid.UUID) ([]OutboxEvent, error) {
	rows, err := q.db.QueryContext(ctx, markOutboxEventsAsSent, pq.Array(ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.Topic,
			&i.Key,
			&i.Type,
			&i.Version,
			&i.Producer,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
			&i.NextRetryAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickPendingOutboxKey = `-- name: PickPendingOutboxKey :one
SELECT e.key
FROM outbox_events e
    LEFT JOIN outbox_key_state ks ON ks.key = e.key
WHERE e.status = 'pending'
    AND e.next_retry_at <= (now() AT TIME ZONE 'UTC')
    AND (ks.blocked_until IS NULL OR ks.blocked_until <= (now() AT TIME ZONE 'UTC'))
ORDER BY e.seq ASC
LIMIT 1
`

func (q *Queries) PickPendingOutboxKey(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, pickPendingOutboxKey)
	var key string
	err := row.Scan(&key)
	return key, err
}
