// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_key_locks.sql

package pgdb

import (
	"context"
	"time"
)

const clearOutboxKeyStateBlock = `-- name: ClearOutboxKeyStateBlock :exec
UPDATE outbox_key_state
SET blocked_until = NULL,
    updated_at = (now() AT TIME ZONE 'UTC')
WHERE key = $1::text
`

func (q *Queries) ClearOutboxKeyStateBlock(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, clearOutboxKeyStateBlock, key)
	return err
}

const deleteStaleOutboxKeyLocks = `-- name: DeleteStaleOutboxKeyLocks :exec
DELETE FROM outbox_key_locks
WHERE stale_at <= (now() AT TIME ZONE 'UTC')
`

func (q *Queries) DeleteStaleOutboxKeyLocks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStaleOutboxKeyLocks)
	return err
}

const getOutboxKeyState = `-- name: GetOutboxKeyState :one
SELECT key, blocked_until, updated_at
FROM outbox_key_state
WHERE key = $1::text
`

func (q *Queries) GetOutboxKeyState(ctx context.Context, key string) (OutboxKeyState, error) {
	row := q.db.QueryRowContext(ctx, getOutboxKeyState, key)
	var i OutboxKeyState
	err := row.Scan(&i.Key, &i.BlockedUntil, &i.UpdatedAt)
	return i, err
}

const tryLockOutboxKey = `-- name: TryLockOutboxKey :one
INSERT INTO outbox_key_locks(key, owner, locked_at, stale_at)
VALUES (
    $1::text,
    $2::text,
    (now() AT TIME ZONE 'UTC'),
    $3::timestamptz
)
ON CONFLICT (key) DO UPDATE
SET owner     = EXCLUDED.owner,
    locked_at = EXCLUDED.locked_at,
    stale_at  = EXCLUDED.stale_at
WHERE outbox_key_locks.stale_at <= (now() AT TIME ZONE 'UTC')
RETURNING key, owner, locked_at, stale_at
`

type TryLockOutboxKeyParams struct {
	Key     string
	Owner   string
	StaleAt time.Time
}

func (q *Queries) TryLockOutboxKey(ctx context.Context, arg TryLockOutboxKeyParams) (OutboxKeyLock, error) {
	row := q.db.QueryRowContext(ctx, tryLockOutboxKey, arg.Key, arg.Owner, arg.StaleAt)
	var i OutboxKeyLock
	err := row.Scan(
		&i.Key,
		&i.Owner,
		&i.LockedAt,
		&i.StaleAt,
	)
	return i, err
}

const unlockOutboxKey = `-- name: UnlockOutboxKey :exec
DELETE FROM outbox_key_locks
WHERE key = $1::text
    AND owner = $2::text
`

type UnlockOutboxKeyParams struct {
	Key   string
	Owner string
}

func (q *Queries) UnlockOutboxKey(ctx context.Context, arg UnlockOutboxKeyParams) error {
	_, err := q.db.ExecContext(ctx, unlockOutboxKey, arg.Key, arg.Owner)
	return err
}

const upsertOutboxKeyStateBlock = `-- name: UpsertOutboxKeyStateBlock :exec
INSERT INTO outbox_key_state(key, blocked_until, updated_at)
VALUES (
    $1::text,
    $2::timestamptz,
    (now() AT TIME ZONE 'UTC')
)
ON CONFLICT (key) DO UPDATE
SET blocked_until = EXCLUDED.blocked_until,
    updated_at = (now() AT TIME ZONE 'UTC')
`

type UpsertOutboxKeyStateBlockParams struct {
	Key          string
	BlockedUntil time.Time
}

func (q *Queries) UpsertOutboxKeyStateBlock(ctx context.Context, arg UpsertOutboxKeyStateBlockParams) error {
	_, err := q.db.ExecContext(ctx, upsertOutboxKeyStateBlock, arg.Key, arg.BlockedUntil)
	return err
}
